# Base image
FROM node:18.14.2-alpine

# Set working directory
WORKDIR /app/server

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose a port (if your application needs to listen on a specific port)
EXPOSE 8080

# Start the application
CMD ["npm", "run", "dev"]